OTP
Wilsonator123/DSS pull request #85
Opened 2024-05-13 14:10 UTC by Sleepy-Git-User

The email version of this branch is still fucked from whatever George did to it last time. So ive removed the logs and given a better example for whoever does the routing. So please review and merge.

2024-05-13 14:16 UTC, Wilsonator123 commented
@Sleepy-Git-User make sure to resolve the conflicts

2024-05-13 14:20 UTC, Sleepy-Git-User commented
Someone else will have todo that. I'm afraid so much has been added to main I'm not sure what is or isn't important. If you could use that git bash thing like you did in the lab that'd be great!

2024-05-13 14:23 UTC, Wilsonator123 requested changes

2024-05-13 14:23 UTC, Wilsonator123 commented on server/utils/fasetup.js
> +  QRCode.toString(otpauth_url,function(err,url){console.log(url);})
Does this actually work for the frontend? What is the return format?

2024-05-13 14:23 UTC, Wilsonator123 commented on server/utils/fasetup.js
is there any endpoint for this? or anywhere its being used outside of the file? Can we get a basic endpoint so that the frontenders can see what endpoint they need to call

2024-05-13 14:23 UTC, Wilsonator123 commented on server/utils/email2fa.js
this doesnt seem to have any functionality or being used anywhere?

2024-05-13 14:24 UTC, Wilsonator123 commented
> se will have todo that. I'm afraid so much has been added to main I'm not sure what is or isn't important. If you could use that git bash thing like you did in the lab that'd be great!

its a package.json file you accept eveything and then run `npm i` and check the server still works

2024-05-13 21:39 UTC, Sleepy-Git-User commented on server/utils/fasetup.js
> +  QRCode.toString(otpauth_url,function(err,url){console.log(url);})
I explained to Alex what the functions do. However I'm not sure how todo the front end bit so gage resources and my best idea of how to

2024-05-13 21:41 UTC, Sleepy-Git-User commented on server/utils/email2fa.js
Yea that file was the start of something that then started its own branch so that can be left

2024-05-14 08:46 UTC, Wilsonator123 commented on server/utils/fasetup.js
> +  QRCode.toString(otpauth_url,function(err,url){console.log(url);})
dont worry, routes is backend and having a acceptable return value is also backend. The frontend can easily say that you are trying to make them do backend

2024-05-14 11:06 UTC, closed without merging